### ISSUE TITLE
[1.10.2]Server messages spamming

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#153]
Futurepack-1.10.2-24.2.133
Left our server on overnight during testing and it spammed this many hundreds or thousands of times:

[Server thread/WARN] [Futurepack]: The Chunk [-429, 935] is currenly not loaded so the state from BlockPos{x=-6849, y=27, z=14962} could not changed to 3, adding this to queed list

**Comment by mcenderdragon** [comment]
Yep this is normal I should remove that log message...

**Comment by mcenderdragon** [comment]
fixed in teh latest 1.10.2 build

-> most likely I meant 1.11

**Comment by SOL3675** [comment]
Hmm... still happened this in my server with Futurepack 24.2.145.
![screenshot from 2017-06-25 16-30-05](https://user-images.githubusercontent.com/16431933/27514433-5b656a18-59c5-11e7-8664-558d6e4383bf.png)
And when this log happened, the server is too laggy. Once it has started, the log is continued if no players
in the server. Can't fix without rebooting server.

**Comment by mcenderdragon** [comment]
Well this is strange, it should at first only happen if somebody is massivly generating chunks and it was removed...

**Comment by SOL3675** [comment]
So, what are these logs mean? Finding spaces that can spawn structures?

**Comment by mcenderdragon** [comment]
This means it has to spawn structures in chunks that are not available jet. In 1.11 this is fixed by npt in 1.10. I think this is also the typo I made.
[This version](http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.146) should fix the spamming.

**Comment by SOL3675** [comment]
Thanks for quick support. I'll try that soon.

**Comment by SOL3675** [comment]
I think it would be fixed in your new version, but I think I need more testing...
