### ISSUE TITLE
[1.12.2] Dungeon Protection destroys placed items.

### ISSUE THREAD

**Issue by MokahTGS** [mcenderdragon/Futurepack-API#281]
The dungeon protection system destroys items when you attempt to place them down.  This is not so bad when you place a torch but very bad when placing down a crate full of stuff.  Boom...gone...with everything inside.

This HAS to have a way of turning it off in the configs or at least change the behavior to NOT destroy items when you try to place something down.

**Comment by mcenderdragon** [comment]
it doesn't destroy stuff. It blocks it. The client maybe things its gone but it is not. Reconnectin g should fix it. THis is a forge/vanilla bug.

**Comment by MokahTGS** [comment]
Well hate to say it but the stuff is gone.   Reconnecting does not fix that

**Comment by mcenderdragon** [comment]
then this is very strange. were it normal blocks or placeable items from other mods.

**Comment by MokahTGS** [comment]
It was a storage crate from actually additions

**Comment by mcenderdragon** [comment]
can you provide a video/gif trying to place one in the dungeon ?

**Comment by MokahTGS** [comment]
Really what good would that do... It just gets removed.   I can try to duplicate it if you want but its not really something a gif would give you any more info on.

**Comment by trogarus** [comment]
Are you sure they're being destroyed? The reason why I ask, is because I have also tried placing items and had them seem to "disappear", but if you go into inventory and click the empty spot in the hotbar, they return =) They do SEEM to disappear though, as they seem to remove from your inventory when placing, but as mentioned before, going into invent and clicking the hotbar place brings them back.

One issue I'm sure relates to this has to do with the top teleporter platform being non removable even after the dungeons are cleared, but maybe I should post a separate issue for this instead of putting it here?

**Comment by mcenderdragon** [comment]
@trogarus yes thanks for making a new issue for this :)

**Comment by zestypanda56** [comment]
did anyone figure this out? because i died inside the dungeon and it wont let me collect my items from my gravestone

**Comment by mcenderdragon** [comment]
It is not allowed for players to break blocks inside the dungeons, so if the grave stone needs to be destroyed inorder to get your items back it wont be possible for you. But there are also gravestone mods wich support right click to get your items.

**Comment by mcenderdragon** [comment]
Also wich gravestone mod do you use ?

**Comment by mcenderdragon** [comment]
as the grave stone mod thing is also fixed I will close this.
