### ISSUE TITLE
CraftTweaker /reload incompatibility

### ISSUE THREAD

**Issue by BSP0p** [mcenderdragon/Futurepack-API#767]
**Mc** 1.16.5, **Forge** 36.0.42, **FP** 31.1.8137, **CraftTweaker** 7.1.0.130

After using the /reload command with CraftTweaker mod installed (without any scripts), most recipes from the Futurepack disappear. Also the /futurepack command stops working.

**To Reproduce**
1. Install Futurepack and CraftTweaker
2. Use /reload
3. Unable to craft most items and use /futurepack command

**Logs**
[Log 1 (from entering the world to reloading)](https://pastebin.com/TPGVzYry)
[Log 2 (after /reload)](https://pastebin.com/TKPrdRB9)

**Comment by mcenderdragon** [comment]
the log indicated mutliple times hhe reload was executed, I also dont see a exception or similar - weird. Does everything work without craftteweaker ?

**Comment by BSP0p** [comment]
Yes, without CraftTweaker everything works fine, but while testing this on my modpack I also noticed that a similar problem occurs with a combination of other mods. Unfortunately I wasn't able to determine which of them could cause this, because the logs did not indicate anything and checking the exact combination from over 100 mods would take several hours.

**Comment by mcenderdragon** [comment]
can you try again with the latest version on curse ? ([link](https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3218368))  The recipe bug should be fixed and I think today I managed to fix the issue with copmmand disappearing.

**Comment by BSP0p** [comment]
Unfortunately, the bug is still present in the latest release. [Log](https://pastebin.com/HGE3ZaNV)

https://user-images.githubusercontent.com/78181661/110120606-8b0b5a00-7dbd-11eb-981b-b033a36e17e2.mp4

**Comment by mcenderdragon** [comment]
@BSP0p /reload takes londer then that atleast for me, so trying after a few seconds should make it appear.

**Comment by pabthelamb** [comment]
This is happening for me on 1.18.2, except I don't have craft tweaker

**Comment by mcenderdragon** [comment]
> This is happening for me on 1.18.2, except I don't have craft tweaker

then its not this issue. What is happening on reload also provide logs and does it also occur with only FUturepack installed ?
